import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Tokopaedi",
  description: "Generated by Tokopaedi",
};

export default function ProductLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return children;
}
