import type { Metadata } from "next";
import { Inter, Handjet, Fugaz_One } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"],variable: '--font-inter' });
const handjet = Handjet({ subsets: ["latin"], variable: '--font-handjet' });
const fugaz_one = Fugaz_One({ subsets: ["latin"], variable: "--font-fugaz-one", weight:"400"});

export const metadata: Metadata = {
  title: "Tokopaedi",
  description: "Generated by Tokopaedi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${handjet.variable} ${fugaz_one.variable}`}
      >
        {/* <Navbar /> */}
        {children}
      </body>
    </html>
  );
}
